# Generated by Django 5.2 on 2025-06-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_users_partner_id_users_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('CISMALE', 'CISMALE'), ('CISFEMALE', 'CISFEMALE'), ('TRANSMALE', 'TRANSMALE'), ('TRANSFEMALE', 'TRANSFEMALE'), ('NONBINARY', 'NONBINARY'), ('INTERSEX', 'INTERSEX'), ('AGENDER', 'AGENDER'), ('OTHER', 'OTHER'), ('PREFERNOTTOSAY', 'PREFERNOTTOSAY')], max_length=100, null=True),
        ),
    ]
