# Generated by Django 5.2 on 2025-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_users_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='partner',
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
