# Generated by Django 5.2 on 2025-06-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='relation_ship_start_date',
        ),
    ]
