# Generated by Django 5.2 on 2025-06-16 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationshiprequest',
            constraint=models.UniqueConstraint(fields=('requester_id', 'receiver_id'), name='unique_relationship_request'),
        ),
    ]
