# Generated by Django 5.2 on 2025-06-16 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationships', '0002_relationshiprequest_unique_relationship_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('user_one', 'user_two'), name='unique_relationship'),
        ),
    ]
