# Generated by Django 5.2 on 2025-06-16 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationships', '0003_relationship_unique_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relationshiprequest',
            name='unique_relationship_request',
        ),
        migrations.RemoveField(
            model_name='relationshiprequest',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='relationshiprequest',
            name='requester_id',
        ),
        migrations.AddField(
            model_name='relationshiprequest',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationshiprequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='relationshiprequest',
            constraint=models.UniqueConstraint(fields=('requester', 'receiver'), name='unique_relationship_request'),
        ),
    ]
