# Generated by Django 5.2 on 2025-04-24 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colorScheme', models.CharField(max_length=255, null=True)),
                ('chatDuration', models.IntegerField(null=True)),
                ('chatOpenTime', models.DateTimeField(null=True)),
                ('wallpaper', models.CharField(max_length=255, null=True)),
                ('theme', models.CharField(choices=[('LIGHT', 'LIGHT'), ('DARK', 'DARK'), ('SYSTEM', 'SYSTEM')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('CISMALE', 'CISMALE'), ('CISFEMALE', 'CISFEMALE'), ('TRANSMALE', 'TRANSMALE'), ('TRANSFEMALE', 'TRANSFEMALE'), ('NONBYNARY', 'NONBYNARY'), ('INTERSEX', 'INTERSEX'), ('AGENDER', 'AGENDER'), ('OTHER', 'OTHER'), ('PREFERNOTTOSAY', 'PREFERNOTTOSAY')], max_length=100, null=True)),
                ('sexuality', models.CharField(choices=[('HETEROSEXUAL', 'HETEROSEXUAL'), ('HOMOSEXUAL', 'HOMOSEXUAL'), ('BISEXUAL', 'BISEXUAL'), ('ASEXUAL', 'ASEXUAL'), ('PANSEXUAL', 'PANSEXUAL'), ('DEMISEXUAL', 'DEMISEXUAL'), ('POLYSEXUAL', 'POLYSEXUAL'), ('OTHER', 'OTHER'), ('PREFERNOTTOSAY', 'PREFERNOTTOSAY')], max_length=100, null=True)),
                ('connectionCode', models.CharField(max_length=255, unique=True)),
                ('partnerId', models.IntegerField(null=True)),
                ('relationShipStartDate', models.DateField(null=True)),
                ('hasAcceptedTermsAndConditions', models.BooleanField(default=False)),
                ('hasAcceptedPrivacyPolicy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivacy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allowStatusVisibility', models.BooleanField(default=False)),
                ('allowBiometric', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcda_api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('userName', models.CharField(max_length=255, unique=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('CISMALE', 'CISMALE'), ('CISFEMALE', 'CISFEMALE'), ('TRANSMALE', 'TRANSMALE'), ('TRANSFEMALE', 'TRANSFEMALE'), ('NONBYNARY', 'NONBYNARY'), ('INTERSEX', 'INTERSEX'), ('AGENDER', 'AGENDER'), ('OTHER', 'OTHER'), ('PREFERNOTTOSAY', 'PREFERNOTTOSAY')], max_length=100, null=True)),
                ('sexuality', models.CharField(choices=[('HETEROSEXUAL', 'HETEROSEXUAL'), ('HOMOSEXUAL', 'HOMOSEXUAL'), ('BISEXUAL', 'BISEXUAL'), ('ASEXUAL', 'ASEXUAL'), ('PANSEXUAL', 'PANSEXUAL'), ('DEMISEXUAL', 'DEMISEXUAL'), ('POLYSEXUAL', 'POLYSEXUAL'), ('OTHER', 'OTHER'), ('PREFERNOTTOSAY', 'PREFERNOTTOSAY')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcda_api.users')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcda_api.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcda_api.users')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='firstUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='mcda_api.users'),
        ),
        migrations.AddField(
            model_name='chat',
            name='secondUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='mcda_api.users'),
        ),
    ]
