# Generated by Django 5.2 on 2025-06-04 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allow_status_visibility', models.BooleanField(default=False)),
                ('allow_last_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
