# Generated by Django 5.2 on 2025-06-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivacy',
            name='allow_last_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprivacy',
            name='allow_status_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
