# Generated by Django 5.2 on 2025-06-24 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_start_date', models.DateField(null=True)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_user_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_one', 'user_two'), name='unique_relationship')],
            },
        ),
        migrations.CreateModel(
            name='RelationshipRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('BLOCKED', 'BLOCKED'), ('NONBINARY', 'NONBINARY'), ('INTERSEX', 'INTERSEX'), ('AGENDER', 'AGENDER'), ('OTHER', 'OTHER'), ('PREFERNOTTOSAY', 'PREFERNOTTOSAY')], max_length=100)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('requester', 'receiver'), name='unique_relationship_request')],
            },
        ),
    ]
