# Generated by Django 5.2 on 2025-09-03 02:51

import apps.Relationships.models
import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshiprequest',
            name='status',
            field=django_mysql.models.EnumField(choices=[('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('BLOCKED', 'BLOCKED'), ('NONBINARY', 'NONBINARY'), ('INTERSEX', 'INTERSEX'), ('AGENDER', 'AGENDER'), ('OTHER', 'OTHER'), ('PREFERNOTTOSAY', 'PREFERNOTTOSAY')], default=apps.Relationships.models.Status['PENDING']),
        ),
    ]
