# Generated by Django 5.2 on 2025-09-03 02:55

import apps.Relationships.models
import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relationships', '0002_alter_relationshiprequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshiprequest',
            name='status',
            field=django_mysql.models.EnumField(choices=[('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], default=apps.Relationships.models.Status['PENDING']),
        ),
    ]
