# Generated by Django 5.2 on 2025-09-03 02:51

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=django_mysql.models.EnumField(choices=[('CISMALE', 'CISMALE'), ('CISFEMALE', 'CISFEMALE'), ('TRANSMALE', 'TRANSMALE'), ('TRANSFEMALE', 'TRANSFEMALE'), ('NONBINARY', 'NONBINARY'), ('INTERSEX', 'INTERSEX'), ('AGENDER', 'AGENDER'), ('OTHER', 'OTHER'), ('PREFERNOTTOSAY', 'PREFERNOTTOSAY')], null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='sexuality',
            field=django_mysql.models.EnumField(choices=[('HETEROSEXUAL', 'HETEROSEXUAL'), ('HOMOSEXUAL', 'HOMOSEXUAL'), ('BISEXUAL', 'BISEXUAL'), ('ASEXUAL', 'ASEXUAL'), ('PANSEXUAL', 'PANSEXUAL'), ('DEMISEXUAL', 'DEMISEXUAL'), ('POLYSEXUAL', 'POLYSEXUAL'), ('OTHER', 'OTHER'), ('PREFERNOTTOSAY', 'PREFERNOTTOSAY')], null=True),
        ),
    ]
