# Generated by Django 5.2 on 2026-03-30 17:57

import cloudinary.models
import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_alter_users_gender_alter_users_sexuality"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="gender",
            field=django_mysql.models.EnumField(
                choices=[
                    ("CISMALE", "CISMALE"),
                    ("CISFEMALE", "CISFEMALE"),
                    ("TRANSMALE", "TRANSMALE"),
                    ("TRANSFEMALE", "TRANSFEMALE"),
                    ("NONBINARY", "NONBINARY"),
                    ("OTHER", "OTHER"),
                    ("PREFERNOTTOSAY", "PREFERNOTTOSAY"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="sexuality",
            field=django_mysql.models.EnumField(
                choices=[
                    ("HETEROSEXUAL", "HETEROSEXUAL"),
                    ("HOMOSEXUAL", "HOMOSEXUAL"),
                    ("BISEXUAL", "BISEXUAL"),
                    ("ASEXUAL", "ASEXUAL"),
                    ("PANSEXUAL", "PANSEXUAL"),
                    ("OTHER", "OTHER"),
                    ("PREFERNOTTOSAY", "PREFERNOTTOSAY"),
                ],
                null=True,
            ),
        ),
    ]
