# Generated by Django 5.2 on 2026-03-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0003_users_profile_picture_alter_users_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
