# Generated by Django 5.2 on 2026-03-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0004_alter_users_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
