# Generated by Django 5.2 on 2026-04-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0006_alter_users_gender_alter_users_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CISMALE", "Homem Cis"),
                    ("CISFEMALE", "Mulher Cis"),
                    ("TRANSMALE", "Homem Trans"),
                    ("TRANSFEMALE", "Mulher Trans"),
                    ("NONBINARY", "Não binaria"),
                    ("OTHER", "Outro"),
                    ("PREFERNOTTOSAY", "Prefiro não dizer"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="profile_picture",
            field=models.URLField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="users",
            name="sexuality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HETEROSEXUAL", "Heterossexual"),
                    ("HOMOSEXUAL", "Homossexual"),
                    ("BISEXUAL", "Bissexual"),
                    ("ASEXUAL", "Assexual"),
                    ("PANSEXUAL", "Pansexual"),
                    ("OTHER", "Outro"),
                    ("PREFERNOTTOSAY", "Prefiro não dizer"),
                ],
                default="",
                max_length=255,
            ),
        ),
    ]
