# Generated by Django 5.2 on 2026-04-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0007_alter_users_gender_alter_users_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profile_picture",
            field=models.URLField(blank=True, default="", max_length=255, null=True),
        ),
    ]
