# Generated by Django 5.2 on 2025-09-03 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_chat_unique_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_open_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
    ]
