# Generated by Django 5.2 on 2025-09-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_alter_chat_chat_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='wallpaper',
        ),
    ]
