# Generated by Django 5.2 on 2025-09-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_remove_chat_wallpaper'),
        ('Relationships', '0003_alter_relationshiprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='relationship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_relationship', to='Relationships.relationship'),
        ),
    ]
