# Generated by Django 5.2 on 2025-09-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_chat_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
