# Generated by Django 5.2 on 2025-09-08 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_alter_chatmessages_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatmessages',
            constraint=models.CheckConstraint(condition=models.Q(('message', ''), _negated=True), name='message_not_empty'),
        ),
    ]
